In [5]:
import numpy as np
snow = np.loadtxt('snow-2007-to-2017.csv',delimiter=',')
snow_cm = snow*2.54
snow_cm

array([[6.98500e+01, 3.88620e+01, 1.14300e+01, 5.58800e+00, 2.54000e-04,
        0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 2.54000e-01,
        1.49860e+01, 7.62000e+01],
       [2.61620e+01, 2.64160e+01, 4.47040e+01, 2.00660e+01, 1.77800e+00,
        0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 5.08000e-01,
        3.30200e+00, 5.30860e+01],
       [3.30200e+01, 9.90600e+00, 5.43560e+01, 5.18160e+01, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 7.64540e+01,
        2.26060e+01, 7.06120e+01],
       [1.16840e+01, 5.81660e+01, 7.28980e+01, 1.47320e+01, 1.42240e+01,
        8.89000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 2.54000e-04,
        5.08000e+00, 2.41300e+01],
       [4.62280e+01, 3.35280e+01, 1.77800e+00, 8.89000e+00, 5.08000e-01,
        0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 2.92100e+01,
        2.18440e+01, 8.40740e+01],
       [1.98120e+01, 8.15340e+01, 2.54000e-04, 4.06400e+00, 2.54000e-04,
        0.00000e+00, 0

In [8]:
#snow depth in average for months in every year
m = np.average(snow,axis = 1) #axis = 1 là tính theo cột
m

array([ 7.12500833,  5.775     , 10.45833333,  6.88334167,  7.41666667,
        5.15835   , 10.46666667,  8.85833333,  9.066675  ,  8.18333333,
        6.36666667])

In [15]:
#snow depth in aver. for year
y = snow.mean(axis = 0)
y

array([12.82727273, 19.48181818, 13.40000909, 13.58181818,  3.32729091,
        0.31819091,  0.        ,  0.        ,  0.04545455,  5.74546364,
        6.42727273, 18.4       ])

In [13]:
#tính theo dòng thif axis = 1
#tính theo cột thì axis = 0
snow.shape

(11, 12)

In [17]:
ar = np.array([1,2,3,4,5,6]).reshape(2,3)
ar

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
ar.mean(axis = 0)

array([2.5, 3.5, 4.5])

### Exercise CS444

In [28]:
b = np.array([[1,2,-3],[3,4,-1]])
a = np.array([2,-5,1,1,4,5,2,-1,6]).reshape(3,3)
#y = np.array([[2],[-4],[1]])
y = np.array([2,-4,1]).reshape(3,-1)
#z = np.array([[-15],[-8],[-22]])
z = np.array([-15,-8, -22]).reshape(3,-1)

In [30]:
ba = np.dot(b,a)
ba

array([[-2,  6, -7],
       [ 8,  2, 17]])

In [33]:
#start from 0, end at 2, create a linear incremental matrix with equal distance 
linspace = np.linspace(0,2,10)
linspace

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [39]:
#creat a matrix with zeros
zeros = np.zeros((2,3),dtype=int)
zeros

array([[0, 0, 0],
       [0, 0, 0]])

In [42]:
#creat a 1 matrix
ones_bool = np.ones((2,3),dtype = bool)
print(ones_bool)
ones = np.ones((2,3),dtype = int)
ones

[[ True  True  True]
 [ True  True  True]]


array([[1, 1, 1],
       [1, 1, 1]])

In [46]:
#random array
randoma = np.random.random((2,3))
randoma

array([[0.20090762, 0.59093919, 0.62221071],
       [0.93015496, 0.47094156, 0.74725808]])

In [58]:
#empty matrix
emp = np.empty((2,3), dtype=int)
emp

array([[0, 0, 0],
       [0, 0, 0]])

In [60]:
X = np.random.rand(1000,1)