In [2]:
import numpy as np
print(np.__version__)

1.18.1


In [5]:
oneD_array = np.array(np.arange(0,10),dtype = np.int)
print(oneD_array)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
#creat 3*3 array of all true
alltrue19 = np.ones(9, dtype=np.bool)
alltrue33 = alltrue19.reshape(3,3)
alltrue33

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [18]:
#another solution
alltrue33_1 = np.full((3,3), True, dtype=bool)
alltrue33_1

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [20]:
#3rd solutoin
alltrue33_2 = np.ones((3,3), dtype = bool)
alltrue33_2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])