# Introduction to numpy

Numpy is the most powerful and basic package for data science

## Create an ndarray = n-dimentional array

In [10]:
import numpy as np
#Method 1: create a 1d array from a list
l = list([1,2,3,4,5])
a = np.array(l)
print('creat an array from a list:\n')
print(a)

#Method2: create a 1d array 



creat an array from a list:

[1 2 3 4 5]


The key difference between an array and a list is, arrays are designed to handle vectorized operations while a python list is not.

That means, if you apply a function it is performed on every item in the array, rather than on the whole array object.

Let’s suppose you want to add the number 2 to every item in the list. The intuitive way to do it is something like this:

In [11]:
#not that easy, will get error
l = l +2
print(l)
#TypeError

TypeError: can only concatenate list (not "int") to list

In [13]:
#but it can do with an array easily 
print('original array:\n')
print(a)
a = a + 2
print('new a: \n')
print(a)

original array:

[3 4 5 6 7]
new a: 

[5 6 7 8 9]


In [16]:
#create 2d array like a matrix with a list of a list
l2 = list([[1,2,3],[4,5,6],[7,8,9]])
a2 = np.array(l2)
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


You may also specify the datatype by setting the dtype argument. Some of the most commonly used numpy dtypes are: 'float', 'int', 'bool', 'str' and 'object'.

To control the memory allocations you may choose to use one of ‘float32’, ‘float64’, ‘int8’, ‘int16’ or ‘int32’.

In [17]:
arr2d_f = np.array(l2, dtype='float')
print(arr2d_f)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
